### ISSUE TITLE
confounds, confounds_df

### ISSUE THREAD

**Issue by juliosolisar** [macartan/gbiqq#102]
We are trying to think through how to get the `confounds_df ` to correctly identify which nodes are confounded with each other given a call to `set_confounds`

Consider the following model with confounder:

```r
model <- make_model("X -> M -> Y") %>%
     set_confounds(list(X = "Y[X=1] > Y[X=0]")
```
The parameter matrix appears to be correctly formed.

In this case X has a different assignment probability for (M01, Y01) and (M10, Y10), so theta_X is confounded with both theta_M and theta_Y. Currently `confound_df ` only "picks up" X, Y confounding.

* Need to really think through this to make sure this understanding is correct
* Need to figure out how to pick up what is confounded; perhaps it can be gleaned from the confound statement, perhaps it requires an analysis of the parameter matrix.

**Comment by lilymedina** [comment]
As I understand this an issue whenever there are nodes that mediate the effect between a parent and a child. So perhaps it'd be good to have a helper function `get_mediators(c("X","Y"))` that returns a list of the nodes that mediate the effect of `X` on `Y`.  I'm guessing you should be able to detect that by inspecting the DAG data frame. Then the mediator nodes would be confounded with the parent, right?

The deprecated function  `get_chains` (see branch [deprecated_functions](https://github.com/macartan/gbiqq/blob/deprecated_functions/R/to_deprecate.R)) might come in handy for this purpose.

**Comment by macartan** [comment]
check against model in 
https://github.com/macartan/gbiqq/issues/41

**Comment by macartan** [comment]
done
