### ISSUE TITLE
Possible bug: Dimension of parameter matrix is different when set_counfounds and set_restrictions are interchanged

### ISSUE THREAD

**Issue by juliancg24** [macartan/gbiqq#103]
`model1 <- make_model("x->y")  %>% set_confound(list(x = "y[x=1]==1"))%>% set_restrictions("x==0")`

`model2 <- make_model("x->y")  %>% set_restrictions("x==0")%>% set_confound(list(x = "y[x=1]==1"))`
`model1`
Parameter matrix: 
 x0.y00 x1.y00 x0.y10 x1.y10 x0.y01 x1.y01 x0.y11 x1.y11 
x0       0      0      0      0      1      0      1      0
x1       0      0      0      0      0      1      0      1
x0       1      0      1      0      0      0      0      0
x1       0      1      0      1      0      0      0      0
y00      1      1      0      0      0      0      0      0
y10      0      0      1      1      0      0      0      0
y01      0      0      0      0      1      1      0      0
y11      0      0      0      0      0      0      1      1

`model2`
 Parameter matrix: 
     x1.y00 x1.y10 x1.y01 x1.y11
x1       0      0      1      1
x1       1      1      0      0
y00      1      0      0      0
y10      0      1      0      0
y01      0      0      1      0
y11      0      0      0      1

**Comment by lilymedina** [comment]
The issue here is that P needs to be updated whenever a confounded model gets reduced. Or in general whenever P is not null.

**Comment by lilymedina** [comment]
fixed in PR https://github.com/macartan/gbiqq/pull/105
