### ISSUE TITLE
summary

### ISSUE THREAD

**Issue by macartan** [macartan/gbiqq#13]
of model -- 

number of parent
share o fP

**Comment by lilymedina** [comment]
> Thoughts on summary -- Moving conversation from email here: 

**DAG** 
A data frame indicating how nodes are related to each other (already attached to model).

**Nodal types**
 A named listed showing the number of types related to each node. Optionally, `verbose = TRUE` would print nodal type names and their interpretation)
`sapply(get_nodal_types(modelXKY), length, USE.NAMES = TRUE)`

**Number of causal types** 
Optionally, `verbose = TRUE` would print causal type names
`nrow(get_causal_types(modeXYK))`

**P's dimensionality** 
`dim(get_parameter_matrix(modelXYK))`

**Restrictions** 
Either report whether the model has been restricted or not. Or show a list of restricted nodal types -- The latter would require attaching and updating list of restricted nodal types. 

**Confounds** 
This information is currently saved as attribute of P--perhaps save condition used for confound?

So output would like:


```
> summary(modelXYK)

$DAG: 
  parent children
2      X        K
3      X        Y
1      K        Y

$Nodal types: 
 X  K  Y 
 2  4 16 

$Causal types
128

$Parameter Matrix
26 Rows
128 Columns

$Restrictions (if any)
`N nodal types have removed from the model`

$Confounds (if any)
 ancestor descendant
1        X          Y

```

**Comment by macartan** [comment]
I think this is great and could be called up by shiny

I do think it important though to have a list of the nodal, or at least
some of them, along with interpretations / how to read these

**Comment by lilymedina** [comment]
ok -- maybe have it as optional and defaulting to TRUE.

**Comment by lilymedina** [comment]
see PR https://github.com/macartan/gbiqq/pull/100
