### ISSUE TITLE
Bug in gbiqq:::restrict_by_labels

### ISSUE THREAD

**Issue by MerlinHeidemanns** [macartan/gbiqq#139]
Note that the first doesn't remove 11 but the second does.
_Code_
model <- make_model("X -> Y")
gbiqq:::restrict_by_labels(model, labels = list(Y = "01", Y = "11"))
_Output_
$Y
00  10  11

  node position display interpretation
1    Y        1   Y[*]*      Y | X = 0
2    Y        2   Y*[*]      Y | X = 1

***Expected***
_Code_
model <- make_model("X -> Y")
gbiqq:::restrict_by_labels(model, labels = list(Y = "?1"))
_Output_
$Y
00  10

  node position display interpretation
1    Y        1   Y[*]*      Y | X = 0
2    Y        2   Y*[*]      Y | X = 1

**Comment by MerlinHeidemanns** [comment]
Added a test that is currently being skipped with a message.

**Comment by macartan** [comment]
good catch
this is fixed now
