### ISSUE TITLE
Lines 36-40 in prep_gbiqq_data.R probably redundant.

### ISSUE THREAD

**Issue by MerlinHeidemanns** [macartan/gbiqq#166]
_Lines_
```
    if (length(l_ends) == 1) {
        l_starts <- 1
    } else {
        l_starts <- c(1, l_ends[1:(n_param_sets - 1)] + 1)
    }
```

_Issue_
If condition is redundant. To access the if condition, the model has to include only one random variable i.e. make_model("X"). But it does not appear possible to generate data with this model. 

_Proposed solution_
Remove if condition and replace with 
```
l_starts <- c(1, l_ends[1:(n_param_sets - 1)] + 1)
```

**Comment by lilymedina** [comment]
Solved in PR [169](https://github.com/macartan/gbiqq/pull/169)
