### ISSUE TITLE
Update set_confounds() syntax

### ISSUE THREAD

**Issue by clarabicalho** [macartan/gbiqq#18]
To match get_type() statement-type syntax

**Comment by macartan** [comment]
there may be  a complexity when layering get_confound; 
imagine we have something like
model %>%
 set_confound(list = (X = "Y[X=0] == Y[X=1]) %>%
 set_confound(list = (X = "Y==1")

the first setting would separate Y00 and Y11 in one block and Y01 and Y10 in another block
the second setting would have to put  YY, X1Y01, X0Y01 into its own block

conceptually that's fine, we have three set of parameters for X assignment, but the tricky thing is that the third will have to steal elements from both of the other two; whereas current procedure, I think, replicates one block and then substitutes
