### ISSUE TITLE
Replace label 'lambda' for 'parameter' when appropriate

### ISSUE THREAD

**Issue by clarabicalho** [macartan/gbiqq#20]
@macartan could run script below and selective commit on Github
```
files <- list.files("R")
sapply(files, function(f){
	fname <- file(paste0("R/", f))
	script <- readLines(fname)
	new_script <- gsub("lambda", "parameter", script)
	writeLines(new_script, fname); close.connection(fname)
})
```

**Comment by clarabicalho** [comment]
@macartan I noticed you changed some terms from 'lambda' to 'parameters' but `lambda` still appears in `draw_data()`, `gbiqq_designer()`, `making_models()`, `prepping_stan()`, `priors()`, and `restriction()`. Just checking that it's fine as is, if so we can close?

**Comment by macartan** [comment]
I think keep it open; it's still a little inconsistent
though am not seeing in /draw_data or simulate_data()
for stan this would have to change in the stan model code also


bookmarking:
I think it might make sense to rename :
  "priors" --> "alpha"
  "prior_distribution" --> priors (its similar to "posterior")

**Comment by clarabicalho** [comment]
Sorry the functions I mentioned are actually file names ("draw_data.R", etc) still containing "lambda".
Is there a rule of thumb for keeping lambda instead of parameter? I can also go over the remaining ones.

**Comment by macartan** [comment]
I tried to pick them off; mostly done I think; we shouldn't change in the
stan prep

btw the designer has not been updated or finished really; it could be good
to work on it a bit as it pulls everything together in one place
