### ISSUE TITLE
allow get_type to have empty bracket

### ISSUE THREAD

**Issue by macartan** [macartan/gbiqq#5]
Y[] == 1

to be interpreted as Y==1 without any application of do operators

**Comment by lilymedina** [comment]
Implemented in simpler. 
You can just write "Y == 1"

`model <- make_model("X"%->%"M", "X"%->%"Y", "M"%->%"Y")
 query <- "(Y==1)
get_types(model, query)

query <- "Y==1 & X[M=0] ==0 "
`
Trying out get_types with many different expressions and it seems robust so far.

**Comment by lilymedina** [comment]
Also, see below the printed output when class of types is logical

```
query <- "(Y[X=1, M = 1] >  Y[X=0, M = 1]) & (Y[X=1, M = 0] >  Y[X=0, M = 0])"

get_types(model, query)

Causal types satisfying query's condition(s)  

 query =  (Y[X=1, M = 1] >  Y[X=0, M = 1]) & (Y[X=1, M = 0] >  Y[X=0, M = 0]) 

X0M00Y0011  X1M00Y0011
X0M01Y0011  X1M01Y0011
X0M10Y0011  X1M10Y0011
X0M11Y0011  X1M11Y0011


 Number of causal types that meet condition(s) =  8
 Total number of causal types in model =  128
```
