### ISSUE TITLE
restrictions' order shouldn't matter

### ISSUE THREAD

**Issue by lilymedina** [macartan/gbiqq#56]
The two scripts below produced different models despite both doing exactly the same.  

Script (b) produces the correct model.

```
# (a)
 model <- make_model("X->Y") %>%
 set_restrictions(causal_type_restrict = c("Y == 0")) %>%
 set_restrictions(causal_type_restrict = c("X == 0"))
 get_parameter_matrix(model)
>     X1.Y10 X1.Y01 X1.Y11
 X1       1      1      1
 Y10      1      0      0
 Y01      0      1      0
 Y11      0      0      1
 attr(,"param_set")
 [1] "X" "Y" "Y" "Y"
```
```
# (b)
 model <- make_model("X->Y") %>%
 set_restrictions(causal_type_restrict = c("X == 0")) %>%
  set_restrictions(causal_type_restrict = c("Y == 0"))
>  get_parameter_matrix(model)
     X1.Y01 X1.Y11
 X1       1      1 
 Y01      1      0
 Y11      0      1
 attr(,"param_set")
 [1] "X" "Y" "Y"
```

**Comment by clarabicalho** [comment]
This is because of line `model$causal_types  <- update_causal_types(model)` in `R/restrictions.R`. Is there a reason why you need to recreate the causal type data frame based on combination of nodal types? When you remove this line, the two chunks above return the same value. See #61.

**Comment by lilymedina** [comment]
good catch! thanks!

That line can be removed from`restrict_causal_types`. Though it is needed in restrict_nodal_types in case the user is restricting nodes and causal types in the same call.

**Comment by lilymedina** [comment]
fixed in PR https://github.com/macartan/gbiqq/pull/61
