### ISSUE TITLE
set_restriction() when `action = "keep"` removing causal types

### ISSUE THREAD

**Issue by clarabicalho** [macartan/gbiqq#60]
Behavior with ` action = "keep"` same as when `action = "remove"`

```
unrestricted <- make_model("X->Y") %>% get_parameter_matrix %>% colnames
restricted <- make_model("X->Y") %>%
set_restrictions(causal_type_restrict = c("Y[X=1] < Y[X=0]"), action = "keep") %>%
get_parameter_matrix %>% colnames
restricted
```
>[1] "X0.Y00" "X1.Y00" "X0.Y01" "X1.Y01" "X0.Y11"
[6] "X1.Y11"

```
setdiff(unrestricted, restricted)
```
> [1] "X0.Y10" "X1.Y10"

**Comment by lilymedina** [comment]
That's right. Thanks for flagging it!

`action` isn't integrated yet for restrictions specified via causal_type_restrict.
It's on my to-do list  (see https://github.com/macartan/gbiqq/issues/55)

**Comment by clarabicalho** [comment]
Yes, but odd that it does restrict even though action set to keep... I could look into #55 along with #36 if OK with you.

**Comment by lilymedina** [comment]
Sounds good to me!

**Comment by lilymedina** [comment]
fixed in PR https://github.com/macartan/gbiqq/pull/61
