### ISSUE TITLE
max data bug

### ISSUE THREAD

**Issue by macartan** [macartan/gbiqq#64]
```
model <- make_model("X -> M -> Y <- X") %>% 
  set_restrictions(causal_type_restrict = "(M[X=1]<M[X=0]) | Y[M=1]<Y[M=0] | (Y[X=1, M=.]<Y[X=0, M=.])")

simulate_data(model)
 Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```

Problem arises in `get_ambiguities_matrix`

```
   A <- sapply(1:nrow(types), function(i)(types$revealed_data[i] == fundamental_data)*1)
>   dim(A)
[1]  8 42
>   A <- matrix(A, ncol = length(type_labels))
>   dim(A)
[1]  7 48
>   length(data_names)
[1] 8
>   colnames(A) <- type_labels
>   rownames(A) <-  data_names
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
```

Incompatibility is here:

```
> nrow(data_realizations)
[1] 42
>
> length(type_labels)
[1] 48
```

From `(get_nodal_types(model))` we should have 48 causal types (2*3*8) but from `get_causal_types' we have just 42.  It's as if some combinations of nodal types are excluded, though these are counterfactually relevant.  For instance causal type   "1 00 0100" is missing from the list of causal types.  Why is that?

**Comment by lilymedina** [comment]
Both causal types and nodal are correct. 

`"1 00 0100`  means that `Y[ X = 1, M = 0]  ` = 1  and `Y[ X = 1, M = 1]  = 1` so that type should be excluded from the model.

But `0100` shouldn't be entirely removed because `Y[M=1] = Y[M=0] = 0`

**Comment by lilymedina** [comment]
So I guess we can't rely on nodal types to create causal types labels.

**Comment by macartan** [comment]
do you mean 
"1 00 0100" means that Y[ X = 1, M = 0] = 1 and Y[ X = 1, M = 1] = **0** 

hmm. I think if we allow for a set of nodal types then we *have* to allow all causal types that are implied by them, since these can all arise with positive probability

In this case I would have though that our restriction means that Y0100 should be removed.  I am not following on why it should not be removed? (We still have Y0000 for the case where X=0)

**Comment by macartan** [comment]
Let's go with this:
* causal types are only removed by a restriction if they cannot be implied by nodal types; in other words * a causal type restriction only matters if it implies nodal types to be removed. 
If a causal restriction does not imply the removal of nodal types then a message should say that tere was no restriction implemented

If users want to implement a causal type restriction without a nodal type restriction then this shoul dbe done via set_confound. eg One could have set_confound(X = list(Y = "01") and then restrict a nodal type for X for some Y types

**Comment by lilymedina** [comment]
Solves in PR https://github.com/macartan/gbiqq/pull/73
