### ISSUE TITLE
collapse_data produces error in 

### ISSUE THREAD

**Issue by lilymedina** [macartan/gbiqq#75]
Trying to run the code below
```
comp_model <- make_model("X->Y<-M")  %>%
set_restrictions(causal_type_restrict = 
"(Y[M=1, X =0] == 1) | 
 (Y[M=0, X =1] == 1) | 
 (Y[M=0, X =0] == 1)") %>%
set_parameter_matrix() %>%
 set_parameters(type = "flat")

data  <-  data.frame(X = c(0,0,0,1,1,1), M = NA, Y = c(0,0,1,0,1,1)) 
given <-  collapse_data(data, comp_model)
possible_data <- make_possible_data_single(comp_model, given, N=1, within = TRUE, "X==1 & Y==1", vars = "M")
```

I get the following error and warning
```
> possible_data
Observations are not consistent with restrictions in 22 cases
Error in A_w %*% possible[, "count"] : non-conformable arguments
```

The issue arises in `collapse_data`  because it's creating rows for events that are not consistent with restrictions.

```
A_w      <- get_likelihood_helpers(comp_model)$A_w
> colnames(A_w)
"M0X0Y0" "M1X0Y0" "M0X1Y0" "M1X1Y0" "M1X1Y1" 


> colnames(comp_model$P)
[1] "M0.X0.Y0000" "M1.X0.Y0000" "M0.X1.Y0000" "M1.X1.Y0000" "M0.X0.Y0001"
[6] "M1.X0.Y0001" "M0.X1.Y0001" "M1.X1.Y0001"
> 
```

This is related to our causal_type/nodal_types discussion.  Previously causal types `"M1.X0.Y0000", "M0.X1.Y0000", "M1.X1.Y0000"` would have been removed from P and, data and causal types would have been conformable.

We probably need to change how data events are being generated in `get_data_events`

**Comment by macartan** [comment]
In this case the model restrictions rule out the possibility of (M=0, Y=1); but this is provided in the df

Perhaps any such operation on data that is inconsistent with the model should first issue a warning that such data is not consistent and then either stop or else proceed with possible data

> gbiqq:::get_max_possible_data(comp_model)
  M X Y
1 0 0 0
2 1 0 0
3 0 1 0
4 1 1 0
5 1 1 1

**Comment by lilymedina** [comment]
Function returns informative warning and stops.

```
comp_model <- make_model("X->Y<-M")  %>%
    set_restrictions(
                         "(Y[M=1, X =0] == 1) | 
 (Y[M=0, X =1] == 1) | 
 (Y[M=0, X =0] == 1)") %>%
    set_parameter_matrix() %>%
    set_parameters(type = "flat")

possible_data <- make_possible_data_single(comp_model, given, N=1, within = TRUE, "X==1 & Y==1", vars = "M")

> Observations are not consistent with restrictions in 5 cases
> Error in A_w %*% possible[, "count"] : non-conformable arguments
```
