### ISSUE TITLE
interpretation of nodal types

### ISSUE THREAD

**Issue by macartan** [macartan/gbiqq#8]
generate this for construction of P matrix, not with reduction of nodal types

**Comment by clarabicalho** [comment]
On interpretation, could we change from current

```
get_nodal_types(make_model("X->M->Y; X->Y")) %>% attr("interpret")
```
>$X
[1] "exogeneous"
$M
[1] "X <- 0" "X <- 1"
$Y
[1] "X <- 0 & M <- 0" "X <- 0 & M <- 1" "X <- 1 & M <- 0"
[4] "X <- 1 & M <- 1"

to something more declarative? For example:

![Captura de Tela 2019-05-28 às 17 57 47](https://user-images.githubusercontent.com/25605156/58493120-8e969980-8172-11e9-913d-3eececff3e52.png)

**Comment by macartan** [comment]
Very nice! It will end up very long. but maybe you could do lookups:
what_is(model, Y[3])
> Y**[*]********
      ^ when X=1 and M = 0& S = 0
which_is(model, Y | X =1 & M=0 & S=0)
> Y**[*]********
      ^ 3rd position
