### ISSUE TITLE
edits to make_priors 

### ISSUE THREAD

**Issue by lilymedina** [macartan/gbiqq#95]
Update make priors so that it operates on nodal types.

The updated function should have the following arguments:
- `model ` (old)
- `prior_distribution` (old) 
- ~~`node`~~ `parameter_set`  (new)
- `statement` to be passed onto `lookup_type` (new)
- `alpha` (old but updated use): 
- `confound` (new and optional)

**Comment by lilymedina** [comment]
Ideas on integrated mapply and general behavior. 

a) `make_priors` could handle  `parameter_set`, `statement`, `alpha`  `confound` with length greater than 1 if they have all the same length.

b) Multiple priors can simultaneously be made for the same `parameter_set`. In that case,  users would enter a single `parameter_set` and multiple `statements` and `alphas` (though of same length)

c) If users enter `alpha` and  `parameter_set` alone, the same value of `alpha `would be applied to all the parameters within the given set.

d) There could be an additional argument called labels via which users can specify parameter_labels. Or `alpha` can be a named list.


For now, will put options b-d to on hold.

**Comment by juliosolisar** [comment]
e) add label options (so user can put Y000, X01...)

**Comment by lilymedina** [comment]
**Write tests for new version of make priors** 

As always, the tests should check that all possible combinations of the functions work as expected and that the function errors when it should.

:point_right: Ideally, the test should check that layering works fine :ok_hand: For example, what happens with priors after a confound? Does calling priors and then confounds produce the same output than confound and then priors? 

Check same behaviour for restrictions and for different combinations of the three functions. 

This is done for confounds and restrictions in the test file `test_layering.R.` 

This a bit of duplicate
