### ISSUE TITLE
integrate get types functions

### ISSUE THREAD

**Issue by lilymedina** [macartan/gbiqq#96]
integrate `get_types`, `get_nodal_types`, `get_causal_types` and `lookup_types` into one function.

The new function, `get_type` would have the following arguments
- `model`
- `statement`: a quoted expression defining a causal statement. If no statement is entered the types returned depend on the value of `nodes`. 
- `nodes`:  A quoted name of the node whose types would be interrogated. Defaults to "ALL"

behavior:
`get_type(model, statement = NULL, nodes = "ALL") `-- should return all units causal types
`get_type(model, statement = NULL, nodes = "X")` -- should return types related to X
`get_type(model, statement = NULL, nodes = c("X", "Y")` -- should return types related to X and Y
`get_type(model, statement = "Y[X=1] > Y[X=0]", nodes = c("Y"))` should return `Y01`
`get_type(model, statement = "Y[X=1] > Y[X=0]", nodes = "ALL")` should return `X0Y01` and `X1Y01`
`get_type(statement = list("X==0","Y[X=1] > Y[X=0]" ),
 nodes = c("X", "Y"))` - `$X  X0` `$Y Y01`
`get_type(model, statement = list("X==0","Y[X=1] > Y[X=0]" ), nodes = c("Y", "X"))` should error

**Comment by macartan** [comment]
@lilymedina  here is an approach to getting rid of the query part of the nodal types function: 
we take the queries and do the same cleaning; but they create a submodel and run get_query_types on the submodel

A function to generate a submodel with a single child:
```
submodel <- function(model, child){
	
	model$dag   <- filter(model$dag, children == child)
	model$nodes <- model$nodes[model$nodes %in% unique(unlist(model$dag))]
	model$nodal_types <- model$nodal_types[names(model$nodal_types) %in% 	model$nodes]
	model$nodal_types[model$nodes != child] <- "1"
	model$causal_types <- NULL
	attr(model, "endogenous_nodes") <- child
	attr(model, "exogenous_nodes")  <- model$nodes[!(model$nodes %in% child)]
	class(model) <- "causal_model"
	model
}
```
A helper:

```
get_last_node <- function(type_vector)
	lapply(strsplit(type_vector, "\\."), function(k) k[length(k)]) %>% unlist
```

The heart of a new lookup function:
```
lookup_nodal_type2 <- function(model, query, node) {

	queries <- submodel(model, node) %>% get_query_types(query)
	names(queries$types) <- get_last_node(names(queries$types))
	queries$type_list    <- get_last_node(queries$type_list)
	queries
	
	}

```

# Example

```
model <- make_model("A -> W -> B -> C <- W")
node = "C"
query <- '(C[B=1, W = 1] > C[B=0, W = 1])'

lookup_nodal_type(model, query)
lookup_nodal_type2(model, query, node)
```

# Example 2

Wonder why the count of types is different here?
```
model <- make_model('M->Y; X->Y')
query <- complements('X', 'M', 'Y')
lookup_nodal_type(model, query)
lookup_nodal_type2(model, query, "Y")
```

**Comment by macartan** [comment]
scratch all that; see new branch with a much simpler approach in which queries are turned into data manipulation expressions and evaluated directly on a potential outcomes table:

```
> model <- make_model('X -> M -> Y; X->Y')
> query <- '(Y[X=0] > Y[X=1])'
> 
> expand_nodal_expression(model, query, "Y") %>%
+ query_to_expression
[1] "(Y[X==0 & M==0, ] > Y[X==1 & M==0, ] | Y[X==0 & M==1, ] > Y[X==1 & M==1, ])"
```

given a dataframe of potential outcomes Y. this last expression evaluates to a vector of true or false statement

**Comment by macartan** [comment]
not integrated but clearer structure now. 

Now have two functions to get the set of types that correspond to a query:
map_query_to_nodal_type
map_query_to_causal_type

Two functions to get the set of types:
get_nodal_types
get_causal_types

Would be possible to have get_nodal_types call map_query_to_nodal_type whenever a query is provided but these perform quite different operations so think best to leave as is.
